apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name  }}-serive-nodeport
spec:
  selector:
    app: web
  type: {{ .Values.service.type  }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.container.port  }}
    nodePort: 30080

